### ISSUE TITLE
Delete removes the file from copied file as well

### ISSUE THREAD

**Issue by dingo-d** [gregnb/filemanager-webpack-plugin#1]
Hi!

Love the plugin, it's just that it has a small flaw. I am developing a plugin, and I want to copy some source files, and put them in the `build/` folder. This works, but if I want to clean the build folder for the assets (javascript file) the same file that I copied will get deleted in the created folder.

```js
new FileManagerPlugin({
  onStart: {
    copy: [
      {source: './src', destination: './build/my-plugin/'}
    ],
    delete: [
      './build'
    ]
  },
  onEnd: {
    copy: [
      {source: './build/scripts', destination: './build/my-plugin/assets/scripts'}
    ],
    delete: [
      './build/my-plugin/skin',
      './build/scripts'
    ]
  }
})
````
So the flow is like this: I am deleting the previously built `build/` folder, then I copy the source in the new folder. This works. Then when the webpack finishes building, I copy the scripts to the newly created folder, and then I delete the source js file located in the `'./build/my-plugin/skin'` folder. 

This all works, and produces the correct result. But if I want to remove the build file that is located in the `build/scripts/` folder the same file that was in that folder gets deleted in the `/build/my-plugin/assets/scripts` folder.

Why is that and how can I remedy this?

I tried moving the file, but that didn't work at all.

**Comment by gregnb** [comment]
@dingo-d Thanks for the feedback. I'll take a look into this issue!

**Comment by gregnb** [comment]
Hey @dingo-d, so I added support for the onStart/onEnd events to accept Arrays. This should preserve the order in which operations happen. Try the following once you upgrade to 1.0.9:

```js
new FileManagerPlugin({
  onStart: [
    {
      copy: [
        {source: './src', destination: './build/my-plugin/'}
      ],
    },
    {
      delete: [
        './build'
      ]
    }
  ],
  onEnd: [
    {
      copy: [
        {source: './build/scripts', destination: './build/my-plugin/assets/scripts'}
      ],
    }
    {
      delete: [
        './build/my-plugin/skin',
        './build/scripts'
      ]
    }
  ]
})
```

**Comment by dingo-d** [comment]
Nope, my `application.js` bundled file is still empty if I delete the `'./build/scripts'` folder.

Maybe those two are linked somehow?

**Comment by gregnb** [comment]
They should not be linked it should be a brand new copy. Could you give me some more details? 

- How many files and how big is the total MB space of build/ after Webpack finishes building?
- Which OS are you running?
- List version of NPM, WebPack, Babel

I'll try to recreate your setup

**Comment by dingo-d** [comment]
Ok, so the bundled .js file is 90KB, the source folder I'm copying is 50KB. There are 23 items in the source that are being copied.

I'm on MacOS HighSierra (v 10.13).
NPM version: 5.5.1
Node version: 8.4.0

My dev dependencies look like this

```sh
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.0",
    "eslint": "^4.5.0",
    "filemanager-webpack-plugin": "^1.0.9",
    "uglifyjs-webpack-plugin": "^0.4.6",
    "webpack": "^3.5.5"
  }
```

I'd show the repo, but it's still private.

Thanks

**Comment by gregnb** [comment]
So I made some more changes if you don't mind upgrading again to the newest version 1.0.10. I believe the problem is happening because the delete operation is firing off before the copy is finished. I've changed the package now to work all operations off promises and they are chained together.  So, if you're following this webpack.config.js sample:

```
new FileManagerPlugin({
  onStart: [
    {
      copy: [
        {source: './src', destination: './build/my-plugin/'}
      ],
    },
    {
      delete: [
        './build'
      ]
    }
  ],
  onEnd: [
    {
      copy: [
        {source: './build/scripts', destination: './build/my-plugin/assets/scripts'}
      ],
    },
    {
      delete: [
        './build/my-plugin/skin',
        './build/scripts'
      ]
    }
  ]
})
```

Looking at 'onStart' it doesn't make much sense to me as you're copying from 'src' into 'build' but then deleting it after? Now, inside of 'onEnd' what we should expect to happen is it will copy from 'build/scripts' into '/build/my-plugin/assets/scripts' and then delete those folders in build.

Anyway, give it a shot!

**Comment by dingo-d** [comment]
On start it first deletes the build folder (cleaning any previous build), then copying from the source. When the bundle is over it deletes the js source from the build copied folder and it should delete the bundled script, but only in the separate bundle folder.

Anyways, after the update it works :) Thanks! :+1:

**Comment by gregnb** [comment]
Great! Thanks for raising the issue it resulted in a nice improvement to the package
