### ISSUE TITLE
Copy file to directory does not work

### ISSUE THREAD

**Issue by protyposis** [gregnb/filemanager-webpack-plugin#10]
```js
new FileManagerPlugin({
  onEnd: {
    copy: [
      {source: '/some/path/somefile.ext', destination: '/some/other/path'},
    ],
  },
});
```

Fails because it seems to try to copy a file onto a directory, as the verbose output suggests:

`FileManagerPlugin: Start copy source file: /some/path/somefile.ext to destination file: /some/other/path`

Expected:

`FileManagerPlugin: Start copy source file: /some/path/somefile.ext to destination file: /some/other/path/somefile.ext`

**Comment by gregnb** [comment]
Yeah, let me think more about this one. I mean, it could end up being a change like:

 if source is a file and destination is a folder, then copy inside folder
 if source is a folder and destination is a folder then overwrite it

but with this at least you can work around it by being explicit 

```
new FileManagerPlugin({
  onEnd: {
    copy: [
      {source: '/some/path/somefile.ext', destination: '/some/other/path/somefile.ext'},
    ],
  },
});
```

**Comment by protyposis** [comment]
Thanks, yes a file should be copied inside a destination folder, and the contents of a source folder should be copied into a target folder while preserving all unrelated files that are already there.

I'm working around like you suggested but it adds unnecessary verbosity, and for the Glob approach it must be possible to specify a target folder anyway.

**Comment by gregnb** [comment]
This has been added to the latest version (1.0.18)
