### ISSUE TITLE
how to user in nuxt?

### ISSUE THREAD

**Issue by luchanan** [gregnb/filemanager-webpack-plugin#100]
could you tell me how to use in nuxt?
```
extend(
        config: WebpackConfiguration,
        ctx: {
          isDev: boolean
          isClient: boolean
          isServer: boolean
          loaders: any
        }
      ): void {
        if (!ctx.isDev && !ctx.isClient) {
          config.plugins?.push(
            new FileManagerPlugin({
              events: {
                onEnd: {
                  archive: [
                    {
                      source: `tar/`,
                      destination: `tar/test.tar.gz`,
                      format: 'tar',
                      options: {
                        gzip: true,
                        gzipOptions: {
                          level: 9
                        },
                        globOptions: {
                          nomount: true
                        }
                      }
                    }
                  ]
                },
              },
            })
          )
        }
```

it works, but the gzip file size is not right

**Comment by sibiraj-s** [comment]
I haven't used nuxt (yet). I think it will be something like.

```js
// nuxt.config.js
module.exports = {
  // ...your nuxt config
  build: {
    plugins: [
      // ... other plugins
      new FileManagerPlugin(),
    ],
  },
};
```

See https://nuxtjs.org/docs/2.x/features/configuration#add-webpack-plugins

**Comment by sibiraj-s** [comment]
> it works, but the gzip file size is not right

Sorry I missed the last line. Could you elaborate this a bit more? I couldn't understand the exact issue here.

**Comment by luchanan** [comment]
> > it works, but the gzip file size is not right
> 
> Sorry I missed the last line. Could you elaborate this a bit more? I couldn't understand the exact issue here.

thanks for reply

this url can test it: [https://github.com/luchanan/nuxt_filemanager_webpack_plugin_test.git](url)

when run script like

```
npm run build
```

it will generate test.tar.gz file. 

when you open it. 

the file is not include .nuxt file. 

so the test.tar.gz sizes is incorrect.

**Comment by sibiraj-s** [comment]
Can you try this.

```js
globOptions: {
  dot: true
}
```

**Comment by luchanan** [comment]
it's useful. thank you
