### ISSUE TITLE
Must use import to load ES Module:

### ISSUE THREAD

**Issue by creepXXX** [gregnb/filemanager-webpack-plugin#102]
// 'use strict'
const FileManagerPlugin = require('filemanager-webpack-plugin')
const path = require('path')

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Creep\Desktop\project_out\kuang-monitor-online\node_modules\filemanager-webpack-plugin\dist\index.js
require() of ES modules is not supported.
require() of C:\Users\Creep\Desktop\project_out\kuang-monitor-online\node_modules\filemanager-webpack-plugin\dist\index.js from C:\Users\Creep\Desktop\project_out\kuang-monitor-online\vue.config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\Creep\Desktop\project_out\kuang-monitor-online\node_modules\filemanager-webpack-plugin\package.json.

**Comment by sibiraj-s** [comment]
Can you try v6.1.1

**Comment by sibiraj-s** [comment]
Should be fixed now.

**Comment by creepXXX** [comment]
resolved
