### ISSUE TITLE
Allow some files to be retained when deleting

### ISSUE THREAD

**Issue by kaysonwu** [gregnb/filemanager-webpack-plugin#106]
## Config

```js
new FilemanagerPlugin({
  context: path.resolve(__dirname, 'public'),
  events: {
    onStart: {
      delete: [
        '**/*',
        '!images',
        '!images/**/*',
        '!.gitignore',
        '!update-browser.html',
      ],
    },
  },
  }),
```

## Issue

I wanted to keep the `images` folder and some files, but they were all deleted.

## Your Environment

| Tech                       | Version |
| -------------------------- | ------- |
| filemanager-plugin-webpack |   6.1.5    |
| node                       |    v14.17.4     |
| OS                         |      macos  big sur 11.4  |

**Comment by sibiraj-s** [comment]
See https://github.com/gregnb/filemanager-webpack-plugin#delete.

Options support ignore property. where you can specify the glob(array) to ignore.
