### ISSUE TITLE
npm ERR! notsup Unsupported engine for filemanager-webpack-plugin@6.1.6:

### ISSUE THREAD

**Issue by codingpierogi** [gregnb/filemanager-webpack-plugin#109]
## Issue

Trying to upgrade from version 6.1.4 to 6.1.6 and I'm now receiving the Unsupported Engine error because I'm using npm 6. It seems weird that I would receive this error in a patch. Also, is there a specific reason for npm 7? 

npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for filemanager-webpack-plugin@6.1.6: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0","npm":">=7.20.0"} (current: {"node":"14.17.5","npm":"6.14.14"})
npm ERR! notsup Not compatible with your version of node/npm: filemanager-webpack-plugin@6.1.6
npm ERR! notsup Not compatible with your version of node/npm: filemanager-webpack-plugin@6.1.6
npm ERR! notsup Required: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0","npm":">=7.20.0"}
npm ERR! notsup Actual:   {"npm":"6.14.14","node":"14.17.5"}

## Your Environment

| Tech                       | Version |
| -------------------------- | ------- |
| filemanager-plugin-webpack |         |
| node                       |         |
| OS                         |         |

**Comment by sibiraj-s** [comment]
It was added for dev environment. Will fix that.

**Comment by sibiraj-s** [comment]
Fixed in v6.1.7
