### ISSUE TITLE
Dependency cpy security vulnerability

### ISSUE THREAD

**Issue by kkmavr** [gregnb/filemanager-webpack-plugin#110]
There is a security issue in the cpy library, because of the glob-parent dependency.
filemanager-webpack-plugin>cpy>globby>fast-glob>glob-parent

An [issue](https://github.com/sindresorhus/cpy/issues/96) has been raised to update to latest versions of their dependencies. If this happens, could you also update to the latest cly version?

**Comment by sibiraj-s** [comment]
Thank you for the notice. If the update for cpy is minor, no changes needed here. If they do a major version release(based on the current unreleased changes in master). I will publish a new version too as soon as I can.

**Comment by JustCarmen** [comment]
Hi, I think I have a similar issue from a dependabot alert

> Dependabot cannot update glob-parent to a non-vulnerable version
The latest possible version that can be installed is 3.1.0 because of the following conflicting dependency:

> filemanager-webpack-plugin@6.1.7 requires glob-parent@^3.1.0 via a transitive dependency on fast-glob@2.2.7

> The earliest fixed version is 5.1.2.

**Comment by sibiraj-s** [comment]
Removed cpy in v7. Its in alpha right now.
