### ISSUE TITLE
Feature request: ignore files 

### ISSUE THREAD

**Issue by dangayle** [gregnb/filemanager-webpack-plugin#112]
Hi. I am using this plugin to copy files from one build over to multiple destinations. There are a few files I do not want to transfer. Right now I have it set to delete the files after the copy event, but I'm hoping you have a cleaner solution to this.

**Comment by sibiraj-s** [comment]
You can use globOptions.

```js
{
  source: 'from-path/**/*.js',
  destination: 'to-path/',
  globOptions: {
     ignore: 'files/**'
  }
}
```

**Comment by dangayle** [comment]
Oh, I missed that. Thank you. There's no way to pass it in as a global
option, is there?

**Comment by sibiraj-s** [comment]
Different action uses different glob dependencies. It's simpler this way.

Closing the issue as it is solved. Feel free to continue the conversation.
