### ISSUE TITLE
npm fix rolls back the version to 2.0.5

### ISSUE THREAD

**Issue by ddehghan** [gregnb/filemanager-webpack-plugin#116]
This breaks our production when we run npm fix.       
      
      Regular Expression Denial of Service in braces - https://github.com/advisories/GHSA-g95f-p29q-9xw4
      fix available via `npm audit fix --force`
      Will install filemanager-webpack-plugin@6.1.7, which is a breaking change
      node_modules/cpx/node_modules/braces
        micromatch  0.2.0 - 2.3.11
        Depends on vulnerable versions of braces
        Depends on vulnerable versions of parse-glob
        node_modules/cpx/node_modules/micromatch
          anymatch  1.2.0 - 1.3.2
          Depends on vulnerable versions of micromatch
          node_modules/cpx/node_modules/anymatch
            chokidar  1.0.0-rc1 - 2.1.8
            Depends on vulnerable versions of anymatch
            Depends on vulnerable versions of glob-parent
            node_modules/cpx/node_modules/chokidar
              cpx  *
              Depends on vulnerable versions of chokidar
              node_modules/cpx
                filemanager-webpack-plugin  1.0.14 - 2.0.5
                Depends on vulnerable versions of cpx
                node_modules/filemanager-webpack-plugin
      
      glob-parent  <5.1.2
      Severity: high
      Regular expression denial of service in glob-parent - https://github.com/advisories/GHSA-ww39-953v-wcq6
      fix available via `npm audit fix --force`
      Will install filemanager-webpack-plugin@6.1.7, which is a breaking change
      node_modules/cpx/node_modules/glob-parent
      node_modules/glob-base/node_modules/glob-parent
        chokidar  1.0.0-rc1 - 2.1.8
        Depends on vulnerable versions of anymatch
        Depends on vulnerable versions of glob-parent
        node_modules/cpx/node_modules/chokidar
          cpx  *
          Depends on vulnerable versions of chokidar
          node_modules/cpx
            filemanager-webpack-plugin  1.0.14 - 2.0.5
            Depends on vulnerable versions of cpx
            node_modules/filemanager-webpack-plugin
        glob-base  *
        Depends on vulnerable versions of glob-parent
        node_modules/glob-base
          parse-glob  >=2.1.0
          Depends on vulnerable versions of glob-base
          node_modules/parse-glob
            micromatch  0.2.0 - 2.3.11
            Depends on vulnerable versions of braces
            Depends on vulnerable versions of parse-glob
            node_modules/cpx/node_modules/micromatch
              anymatch  1.2.0 - 1.3.2
              Depends on vulnerable versions of micromatch
              node_modules/cpx/node_modules/anymatch
      
      9 vulnerabilities (2 low, 7 high)
      
      To address all issues (including breaking changes), run:
        npm audit fix --force

## Config

dose not matter here.

## Issue

There is some dependency in the package that is not secure and it causes it to be rolled back. 

## Your Environment

"filemanager-webpack-plugin": "6.1.7",
OSX
node 16.14.2

**Comment by sibiraj-s** [comment]
Can you try. v7.0.0.beta.0. It should be free from vulnerable dependencies.

**Comment by ddehghan** [comment]
thank you very much for quick response. it works for me.
