### ISSUE TITLE
Can not copy a directory into another directory

### ISSUE THREAD

**Issue by joket1999** [gregnb/filemanager-webpack-plugin#124]
## Config
`
onEnd: {
  copy: [{ source: './src/images', destination: './dist/' }]
}
`

## Issue
I want to copy the `images` directory into `dist` directory, but it just copy the files in `images`  without `images`

## Your Environment

| Tech                       | Version |
| -------------------------- | ------- |
| filemanager-plugin-webpack |   8.0.0      |
| node                       |    18.6.0     |
| OS                         |   MacOS 10.15.7      |

**Comment by sibiraj-s** [comment]
why not do

```js
onEnd: { copy: [{ source: './src/images', destination: './dist/images/' }] }
```
?
