### ISSUE TITLE
Latest version is still not working

### ISSUE THREAD

**Issue by redaxmedia** [gregnb/filemanager-webpack-plugin#13]
## Config
```
{
  source: './node_modules/material-design-icons/1.svg',
  destination: './dist/assets/material-design-icons/'
},
{
  source: './node_modules/material-design-icons/{2}.svg',
  destination: './dist/assets/material-design-icons/'
}

```
## Issue

Sorry, but something is going wrong, again.

1. Creates a file named `material-design-icons` under `./dist/assets`
 1.1 File vs. directory handling is messed up

2. Does nothing

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |1.0.17|
| node        | v8.7.0|
| OS      |Ubuntu 17|

## Testing

The way you are unit testing does not follow the best practices.

1. You are working with fixture files - examples is a misleading word here
 1.1 I suggest to use a mocking library¹ for the filesystem as you need to perform lot of testing
1. You did not cover all possible configs to use your library - add more test cases
1. Optional: Create a `test` folder with ` {ClassName}Test.js` files
1. Optional: Use Jasmin or Mocha

¹https://github.com/snowmantw/Fe

**Comment by gregnb** [comment]
@redaxmedia Sorry for the frustration this is causing you. In retrospect, me jumping from cpr to cpx without the unit tests first was a failure on my part.  I tried over the weekend to put the groundwork towards unit testing but clearly there are many more tests to be done.

The mocking library I will look into over the weekend. For now,  I'll take a look at this issue in a minute and add the tests in after the fix

**Comment by gregnb** [comment]
@redaxmedia I'm trying to replicate your issue and I don't see a problem with #2 -- I've installed the exact package 

npm install material-design-icons

then went ahead and found a couple svg's from this package copy over into dist:

> { 
  source: './node_modules/material-design-icons/editor/svg/design/{ic_wrap_text_18px,ic_wrap_text_24px,ic_wrap_text_48px}.svg', 
   destination: './dist/assets/reduxmedia-folder-does-not-exist-yet-svg/'
}

Now when I look inside of dist

 ls -lasl dist/assets/reduxmedia-folder-does-not-exist-yet-svg
total 24
0 drwxr-xr-x  5 gnowakow  G\Domain Users  170 Dec 18 08:38 .
0 drwxr-xr-x  5 gnowakow  G\Domain Users  170 Dec 18 08:38 ..
8 -rw-r--r--  1 gnowakow  G\Domain Users  297 Dec 18 08:38 ic_wrap_text_18px.svg
8 -rw-r--r--  1 gnowakow  G\Domain Users  271 Dec 18 08:38 ic_wrap_text_24px.svg
8 -rw-r--r--  1 gnowakow  G\Domain Users  279 Dec 18 08:38 ic_wrap_text_48px.svg

**Comment by redaxmedia** [comment]
First, don't worry - no frustration here... we are all professionals :-)
Good to see that you learned your lesson anyway. Using a solid unit testing suite before a refactoring is a must have... :+1: 

Working: `../../{ic_wrap_text_18px,ic_wrap_text_48px}.svg`
Not working: `../../ic_wrap_text_48px.svg`

**Comment by gregnb** [comment]
So I've made another update, but it raises some questions so i'm not publishing up to NPM just yet. Take for example the following:

```
   { source: "./path/file-to-copy.ext", destination: "./destination/" },
```
that will copy 'file-to-copy.ext' into 'destination' **if destination exists** after the fix.

now when this gets tricky say I provide the following:

```
  { source: "./dist/bundle.js", destination: "./does-not-exist/" },
```

it'll copy over bundle.js to ./does-not-exist. Now, if the path doesn't exist I guess the best check I can think of is looking for a trailing slash? What if they specified:

```
  { source: "./dist/bundle.js", destination: "./does-not-exist" },
```

Wonder if at some point I get someone complaining about trying to copy over files that don't end in an extension.

**Comment by redaxmedia** [comment]
I think everything without an extension should be handled as a directory - trailing slash or not, this is not a fail-safe approach.

**Comment by gregnb** [comment]
>I think everything without an extension should be handled as a directory - trailing slash or not, this is not a fail-safe approach.

@redaxmedia I'll go with the approach of treating everything as a directory then if it has no file extension. I'll push out an update later tonight. This update will also close #10

**Comment by gregnb** [comment]
Update has been applied to 1.0.18

**Comment by redaxmedia** [comment]
Latest version is woking for me - thank you :-)

**Comment by gregnb** [comment]
No problem! Thank you for your help
