### ISSUE TITLE
Thank you!!!

### ISSUE THREAD

**Issue by rococode** [gregnb/filemanager-webpack-plugin#14]
Disclaimer: not an actual issue haha

Just found this plugin [here](https://github.com/webpack-contrib/copy-webpack-plugin/issues/15) and wanted to say THANK YOU. So great to see someone actually go and create some functionality they needed, and even greater that it's PERFECT for my own uses! Will be using this in several of my projects (for some hacky Java-Typescript interop..)

**Comment by gregnb** [comment]
@rococode Thanks for the feedback man! Really appreciate it. I'm glad this is going to help you out
