### ISSUE TITLE
 "material-design-icons": "^3.0.1",

### ISSUE THREAD

**Issue by libetl** [gregnb/filemanager-webpack-plugin#15]
## Issue
Hello,
Why do we pull material-design-icons as npm dependency ?
Is it necessary ?
My npm install is 3 times longer than it used to be because of that.
![image](https://user-images.githubusercontent.com/1233790/34486855-093ddbaa-efd2-11e7-893f-80da975164bf.png)

Thanks.

**Comment by libetl** [comment]
Thanks for your new release !

**Comment by gregnb** [comment]
Wow, thanks for pointing this out. This was a screw up on my part. I'm working on publishing it shortly it'll be version 1.0.19
