### ISSUE TITLE
Recognize and translate [hash] stats.

### ISSUE THREAD

**Issue by rafael-brandao** [gregnb/filemanager-webpack-plugin#17]
## Config
```javascript
const FileManagerPlugin = require("filemanager-webpack-plugin");

module.exports = env => {
  const outputPath = `${__dirname}/build`;
  const distPath = `${__dirname}/dist`;
  
  return {
    entry: { "fancy-project": `${__dirname}/src/index.js`},
    output: {
      filename: "bundle.[hash].js",
      path: outputPath
    },
    plugins: [
      new FileManagerPlugin({
        onStart: [{
          delete: [distPath, outputPath]
        }, {
          mkdir: [distPath]
        }],
        onEnd: [{
          copy: [{
              source: `${outputPath}/bundle.[hash].js`, 
              destination: `${distPath}/bundle.js`
          }]
        }]
      })
    ]
  };
};
```

## Issue
The plugin crashes because it does not translate the `[hash]` part of the file to the correct hexadecimal sequence hash of the build and ends up not finding the source file.
```
node_modules/filemanager-webpack-plugin/lib/index.js:331
                        if (sStats.isFile()) {
                                   ^

TypeError: Cannot read property 'isFile' of undefined
    at node_modules/filemanager-webpack-plugin/src/index.js:112:36
    at FSReqWrap.oncomplete (fs.js:167:5)
```
It would be really nice to have this feature. I have to use another plugin that correctly translates stats like [hash] just for this. It would be nice to take a look, it's a very simple plugin compared to filemanager-webpack-plugin:

WebpackCopyOnBuildPlugin
https://github.com/GitSage/webpack-copy-on-build-plugin

## Your Environment
| Tech                                              | Version |
|-------------------------------------|-------------|
| filemanager-plugin-webpack       |     1.0.19    |
| node                                             |     v9.3.0     |
| OS                                                 |     Arch Linux 4.14.8-ARCH Wed Dec 20 21:27:44 UTC 2017 x86_64 GNU/Linux    |

**Comment by gregnb** [comment]
Thanks for sharing this with me. I think this is pretty useful and I'll investigate tonight!

**Comment by gregnb** [comment]
This feature is now added in 1.0.20
