### ISSUE TITLE
Support for wildcards

### ISSUE THREAD

**Issue by redaxmedia** [gregnb/filemanager-webpack-plugin#2]
Hello,

It would be great to work with [glob](https://www.npmjs.com/package/glob) to support wildcards.

Unfortunately [cpr](https://www.npmjs.com/package/cpr) does not support this, so I suggest to use another library such as [cpx](https://www.npmjs.com/package/cpx) maybe?

I would send you a pull request but without unit testing this ain't fun :-)

Thank you for the plugin anyway.

**Comment by gregnb** [comment]
When I first starting working on this I had some issues with cpx. If you want todo some thorough testing and present a good case for it having no issues I'd be glad to take a PR!

**Comment by redaxmedia** [comment]
Like I said... without a testing suite I don't plan to send a pull request as I cannot do TDD.

But you can keep this issue open, maybe someone else will do it.

**Comment by cypherix93** [comment]
If `onStart` and `onEnd` could take callbacks, maybe we could create the globs ourselves using [glob](https://www.npmjs.com/package/glob). What do you think?

**Comment by gregnb** [comment]
I've updated the package to now use cpx. Should take care of your issues

**Comment by redaxmedia** [comment]
Great move... I'll give it a try soon. Now closing this issue. Thanks!
