### ISSUE TITLE
Destination filename hashing

### ISSUE THREAD

**Issue by kroko** [gregnb/filemanager-webpack-plugin#21]
## Config

```javascript
new FileManagerPlugin({
  onStart: {
    copy: [
      {
        source: 'src/preflight.js',
        destination: 'public/assets/[name].[hash].[ext]'
      }
    ],
    move: [],
    delete: [],
    mkdir: []
  },
  onEnd: {}
});
```

## Issue

Would be nice if output files could be hashed.

I.e. `copy-webpack-plugin` allows

```javascript
new CopyWebpackPlugin([
  {
    from: 'src/preflight.js',
    to: '[name].[hash].[ext]' // results in public/assets/preflight.mumbojumbo.js
  }
]);
```

Thanks!

## Your Environment

| Tech         | Version
| ---------------- | -------
| node             | 8.9.4
| npm              |  5.6.0
| Operating System |  macOS 10.13.2
| Webpack |  3.10.0
| filemanager-plugin-webpack  |  1.0.21

**Comment by gregnb** [comment]
Sounds reasonable, I'll take a look into this tonight. Thanks!

**Comment by kroko** [comment]
Of course hash being dependant on file content, it changes when file (content) changes, not something randomly new on every build.

**Comment by gregnb** [comment]
@kroko That is going to conflict with what Webpack already provides for filename substitutions. 

https://webpack.js.org/configuration/output/#output-filename

So I can provide those filename substitutions from Webpack for [hash] but not a custom one that is based on file content changing

**Comment by kroko** [comment]
Better that than nothing 😄

**Comment by gregnb** [comment]
@kroko Hah, sounds good man. In 1.0.24 you can use [hash] for your destinations

**Comment by garyvh2** [comment]
@gregnb Is there a way to make this work `onStart`? currently it only works `onEnd`

Regards
