### ISSUE TITLE
Issue copying file without extension

### ISSUE THREAD

**Issue by themikesnow** [gregnb/filemanager-webpack-plugin#25]
## Config

```javascript
new FileManagerPlugin({
      onEnd: [
        {
          copy: [
            { source: '_redirects', destination: './build/' },
          ],
        },
      ],
    }),
```

## Issue

  Hi Guys,
     I am having a little issue while using the plugin (which by the way is very useful! :)). I have a file which does not have an extension that needs to be copied into the build directory. For some reason the file gets created under a new directory with the same name (_redirects) instead of just copying the file. Is there any flag I can set to let the plugin know the destination needs to be created as a file and not a directory? Even tho there is no extension?

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |    1.0.26     |
| node        |     v8.9.3    |
| OS      |    mac     |

**Comment by gregnb** [comment]
Hey Mike,

Thanks for the feedback. I had a feeling this day would come when I posted this comment: https://github.com/gregnb/filemanager-webpack-plugin/issues/13#issuecomment-352461176

I will leave this issue open and see if others voice their need for such a feature

**Comment by mikevaleriano** [comment]
Exactly my problem there.

OP is probably deploying to Netlify as well, as `_redirects` is the file they use to control redirect and rewrite rules.

For now I'm using [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin), which is limited in comparison, but gets this specific job done painlessly.

**Comment by yannicke** [comment]
Same problem for me with the _redirects file when deploying to Netlify.
It will be great to be able to copy file without extension!

**Comment by yannicke** [comment]
I made an update to allow copy file without extension with a "toType" property.

It works for me now with: { source: '_redirects', destination: './dist/_redirects', toType: 'file' }

#58

**Comment by zicodeng** [comment]
Same problem here, any updates on when we will resolve this bug?

**Comment by sibiraj-s** [comment]
It is fixed now. try. v3-alpha.

**Comment by sibiraj-s** [comment]
Reopen if it doesn't work.
