### ISSUE TITLE
[question] What is the order of operations of the options?

### ISSUE THREAD

**Issue by akhoury** [gregnb/filemanager-webpack-plugin#26]
[`copy`, `move`, `delete`, `mkdir`, `archive`] is that it?

**Comment by gregnb** [comment]
The order of executed operations are what you provide in the config. It should be going through each one in a synchronous fashion.  Are you having any issues?

**Comment by akhoury** [comment]
I am not thank you, I am just wondering if there was a strict order, since [properties order in objects is not guaranteed in JavaScript](https://stackoverflow.com/a/5525820/493756)

**Comment by gregnb** [comment]
@akhoury Yep, understood. In the README near the bottom I also list a way where you can provide these in as an array if you have any issues: https://github.com/gregnb/filemanager-webpack-plugin

**Comment by akhoury** [comment]
Awesome, thanks so much !

**Comment by gregnb** [comment]
@akhoury No problem!
