### ISSUE TITLE
Override cprOptions

### ISSUE THREAD

**Issue by clockworked247** [gregnb/filemanager-webpack-plugin#3]
I want to be able to override the default cpr optons.  For instance, I don't want "deleteFirst" set to true when copying files into a directory.  I want to leave the directory contents intact. 

Sending PR to add this functionality.  Thanks for considering.

**Comment by gregnb** [comment]
I see you closed the PR. I was going to comment it needed work. Do you still want to explore this issue and reopen or you're all set ?
