### ISSUE TITLE
Archive file includes empty copy of itself

### ISSUE THREAD

**Issue by atdiff** [gregnb/filemanager-webpack-plugin#30]
## Config

```
new FileManagerPlugin({
        onEnd: {
            archive: [
                {
                    source: './dist',
                    destination: './dist/dist.zip',
                    format: 'zip'
                }
            ]
        }
    })
```

## Issue

The dist.zip file that gets created ends up containing a dist.zip that is empty. Shouldn't dist.zip exclude itself?

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  | 1.0.26 |
| node        | 10.1.0 |
| OS      | Windows 7 |

**Comment by gregnb** [comment]
I would choose a different destination

**Comment by atdiff** [comment]
That's the route I ended up going. But it would be nice if the plugin was smart enough to just exclude that file altogether.

**Comment by HawkeyePierce89** [comment]
+1 to topicstarter, it's this is a logical configuration, if I don't want to clutter up the project folder
