### ISSUE TITLE
'move' does not work =>  path does not exist | 'copy' no error

### ISSUE THREAD

**Issue by fillon** [gregnb/filemanager-webpack-plugin#33]
## Config
```
new FileManagerPlugin({
                onEnd: [
                    {
                        mkdir: [path.join(paths.buildRoot, 'htdocs')],
                        //SF180709 'copy' works, 'move' path does not exist
                        move: [
                            {
                                source: path.join(paths.dist, 'manifest*.json'),
                                destination: path.join(
                                    paths.buildRoot,
                                    'htdocs/.'
                                )
                            }
                        ]
                    }
                ]
            })
```
## Issue
When using 'move', I get the following message:  
`Warning:   - FileManagerPlugin: Could not move /Users/aa/projects/foo/dist/manifest*.json: path does not exist`

When using 'copy', it copies the file without any error.

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |   1.0.27      |
| node        |     10.5.0    |
| OS      |    macOS 10.12.6     |

**Comment by EliasJorgensen** [comment]
I am experiencing the same issue. When trying to move a file it complains when the above error message, but it works flawlessly when using copy.
My temporary workaround is copying the file, and then deleting the old file.

**Comment by EliasJorgensen** [comment]
My issue was unrelated. See #36.

**Comment by sibiraj-s** [comment]
Sorry for the delayed reply. I just started maintaining this lib.

When you are using objects. the execution order is not guaranteed. See here for example https://github.com/gregnb/filemanager-webpack-plugin#order-of-execution

Try this.

```js
new FileManagerPlugin({
  onEnd: [
    {
      mkdir: [path.join(paths.buildRoot, "htdocs")],
    },
    {
      //SF180709 'copy' works, 'move' path does not exist
      move: [
        {
          source: path.join(paths.dist, "manifest*.json"),
          destination: path.join(paths.buildRoot, "htdocs/."),
        },
      ],
    },
  ],
});
```

Reopen if the issue still exists.
