### ISSUE TITLE
Differentiate between incremental and full Webpack build

### ISSUE THREAD

**Issue by nchen63** [gregnb/filemanager-webpack-plugin#34]
## Config

```
         onStart: {
             delete: [
                 "./dist",
             ],
         },
```

## Issue

Would be nice if the plugin could support events that only occur on full Webpack build. For example, I want to delete all of the files in the target before building. Currently, it deletes everything even on incremental watch builds. Webpack doesn't appear to write unchanged files, so all the files get deleted and most of the files I need are missing.

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |  1.0.26       |
| node        |    v9.10.1     |
| OS      |     OSX    |

**Comment by sibiraj-s** [comment]
You can now use `runOnceInWatchMode` to execute the `onStart` event to run only once in watch mode. Added in v6.1.0
