### ISSUE TITLE
move cannot use the product of previous action, while copy can

### ISSUE THREAD

**Issue by EliasJorgensen** [gregnb/filemanager-webpack-plugin#36]
## Config
```javascript
new FileManagerPlugin({
  onEnd: [
    {
      copy: [
        { source: "./dist/bundle.js", destination: "./testing/moveCopiedFile.js" },
      ],
    },
    {
      archive: [
        { source: "./dist/**/*", destination: "./testing/moveGeneratedFile.tar", format: "tar" },,
      ],
    },
    {
      move: [
        { source: "./testing/moveGeneratedFile.tar", destination: "./testing/testing7/movedGeneratedFile.tar" },
        { source: "./testing/moveCopiedFile.js", destination: "./testing/testing7/movedCopiedFile.js" },
      ],
    },
  ],
})
```

## Issue

When i am trying to move an archive that i just generated, i receive   
`Warning:   - FileManagerPlugin: Could not move ./testing/moveGeneratedFile.tar: path does not exist`  
`Warning:   - FileManagerPlugin: Could not move ./testing/moveCopiedFile.js: path does not exist`.  
I would assume that the expected behavior of running the actions in series, opposed to running them in parallel, would be that one was able to manipulate the product of the previous action. This is not the case with `move`.

if i however use `copy`, like this:  
```javascript
new FileManagerPlugin({
  onEnd: [
    {
      copy: [
        { source: "./dist/bundle.js", destination: "./testing/moveCopiedFile.js" },
      ],
    },
    {
      archive: [
        { source: "./dist/**/*", destination: "./testing/moveGeneratedFile.tar", format: "tar" },,
      ],
    },
    {
      copy: [
        { source: "./testing/moveGeneratedFile.tar", destination: "./testing/testing7/movedGeneratedFile.tar" },
        { source: "./testing/moveCopiedFile.js", destination: "./testing/testing7/movedCopiedFile.js" },
      ],
    },
  ],
})
```
It will work just fine.

I have created a fork of the project, where i have written a couple of tests to reproduce the issue:  
https://github.com/EliasJorgensen/filemanager-webpack-plugin  

I will try to hunt down the issue on my own, if i find the time.

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |    v1.0.28     |
| node        |    v10.7.0     |
| OS      |    Ubuntu 16.04     |

**Comment by gregnb** [comment]
Especially since:

https://github.com/gregnb/filemanager-webpack-plugin/blob/master/src/index.js#L325

That promise should not resolve until the archive is finalized

**Comment by sibiraj-s** [comment]
Fixed in v3. Reopen if the issue still persist.
