### ISSUE TITLE
Generated archive file is included in the generated archive if the destination file is a child of the source folder

### ISSUE THREAD

**Issue by jimwheaton** [gregnb/filemanager-webpack-plugin#37]
## Config
```
new FileManagerPlugin({
      onEnd: {
        archive: [
          {
            source: 'dist',
            destination: 'dist/mypackage.zip'
          }
        ]
      }
    })
```

## Issue
If the archive destination filename is specified as a child of the source folder, then the .zip file itself is zipped and included in the .zip archive.  For example, let's say my /dist folder has these files:

a.html
b.html

and I archive this folder using the config above. Then the dist folder will have:

a.html
b.html
mypackage.zip

However, if I unzip mypackage.zip, I'll see these files:

a.html
b.html
mypackage.zip 

Obviously I don't want `mypackage.zip` to be included in the zip file. I would expect to see just these two files when I unzip:

a.html
b.html

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |    1.0.27     |
| node        |  10.5         |
| OS      |   macOS High Sierra 10.13.6      |

**Comment by gregnb** [comment]
Issue is now fixed thanks to @pnobbe

**Comment by pnobbe** [comment]
@gregnb Might want to revert the PR and open this issue again. Noticed some unwanted behaviour that the tests didn't cover that occured in the PR. I'll get on it soon.
