### ISSUE TITLE
Avoid execution in watch mode

### ISSUE THREAD

**Issue by uoziod** [gregnb/filemanager-webpack-plugin#45]
That would be awesome to be able to execute onStart only once in watch mode.

**Comment by salvatoredibenedetto** [comment]
Yes absolutely agree with @uoziod .
I need to remove files only once at-start not on recompile.
That would be great

**Comment by hummal** [comment]
Made a pr to execute only once if watch mode is enabled. That should fit most of the use cases.

**Comment by sibiraj-s** [comment]
Fixed in v6.1.0
