### ISSUE TITLE
resource busy or locked error

### ISSUE THREAD

**Issue by soubhratra** [gregnb/filemanager-webpack-plugin#46]
## Config
new FileManagerPlugin({
        onEnd: [
         {
            copy: [
              {
                source: "./target/dist/bundle.js",
                destination: "C://my_grails_project/main/web-app/client-lib/react-component"
              }
            ]
          }
        ]
      })

## Issue
I am building a shared Javascript library in react which is getting bundled with a Grails / Backbone application. The general integration and build process (Maven/Grunt/Webpack) works fine. To facilitate  developers to make change in the component locally and immediately reflect that change in grails application (which is also running locally), I tried to use filemanager plugin but getting the below error - 
I am running webpack dev with watch mode so that webpack build gets kicked of on any react file change. Then on onEND event, I want filemanager plugin to copy the bundle.js to my grails client-lib folder (which grails watches and deploys immediately).

{ Error: EBUSY: resource busy or locked, unlink 'S:\my_grails_project\main\web-app\client-lib\react-component\bundle.js'
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'S:\\my_grails_project\\main\\web-app\\client-lib\\react-component\\bundle.js' }

This works fine if I use windows copy command from command line (but that's what I am trying to avoid)
copy /y target\dist\bundle.js s:\my_grails_project\main\web-app\client-lib\react-component

Appreciate any help

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |   ^2.0.5      |
|webpack | ^4.16.5 |
|webpack-cli | ^3.1.0 |
| node        |    v8.9.1     |
| OS      |    windows     |

**Comment by sibiraj-s** [comment]
Sorry for the delay reply. I just joined this lib as a collaborator. 
If you still have the problem Can you try it with v3 and reopen if required.
