### ISSUE TITLE
Copying files in `onStart` doesn't seem to cause webpack to wait before compiling

### ISSUE THREAD

**Issue by eamodio** [gregnb/filemanager-webpack-plugin#47]
## Config

```
		new FileManagerPlugin({
			onStart: [
				{
					copy: [
						{
							source: path.resolve(__dirname, "../other/src/shared/*"),
							destination: "src/shared/"
						}
					]
				}
			],
```

## Issue

When using the following config, Webpack doesn't seem to wait for the copy operation to complete before it continues and starts compiling. I am copying in some shared typescript files (that are required for the build to succeed) and for the longest time it was working fine (since there was only 2 tiny files), now because there are 8 files (with more content) my builds started failing. It looked like with just the 2 files the copy happened fast enough before the compile started, but with more it never succeeds.

This doesn't feel like expected behavior -- is there a setting I'm missing or is this a bug?

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |   2.0.5      |
| webpack        |     4.20.2    |
| node        |     8.12.0    |
| OS      |    Windows 10 x64     |

**Comment by gregnb** [comment]
hey @eamodio so like most plugins we're simply attaching to the hooks provided to let us know when a build has finished.  I don't know if we can pause/interrupt that process from the plugin space. It may be possible? in order to solve your issue outlined above we would need something like this

**Comment by sibiraj-s** [comment]
Fixed in v3 alpha.
