### ISSUE TITLE
Preserve original date when copying files

### ISSUE THREAD

**Issue by ConnorsFan** [gregnb/filemanager-webpack-plugin#48]
## Issue
I want to copy many files from one folder to another one, and keep the original file modification date.  As it is now, the current date and time is set on the copied files.

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  | 2.0.5  |
| node        |  8.9.1  |
| OS      |  Windows 7  |

**Comment by sibiraj-s** [comment]
Fixed in v3-alpha.7
