### ISSUE TITLE
Vulnerability on braces < 2.3.1

### ISSUE THREAD

**Issue by dotnetshadow** [gregnb/filemanager-webpack-plugin#49]
Hi there,

## Config
filemanager-webpack-plugin 2.0.5

## Issue
There is a vulnerability on braces package < 2.3.1
https://www.npmjs.com/advisories/786

**Comment by soundasleep** [comment]
While this vulnerability exists, you may want to consider the alternative plugin https://github.com/webpack-contrib/copy-webpack-plugin which has very similar behaviour (and has no vulnerabilities at the moment).

**Comment by dotnetshadow** [comment]
@soundasleep cheers, thanks for that unfortunately I need to delete a directory
I went with https://github.com/johnagan/clean-webpack-plugin

**Comment by Wyzix33** [comment]
Any news on this?

**Comment by sibiraj-s** [comment]
Recently a new version is published which fixes most of the vulnerability. some required breaking changes which is available in v3(alpha)
