### ISSUE TITLE
Exclude certain files in archive?

### ISSUE THREAD

**Issue by dingo-d** [gregnb/filemanager-webpack-plugin#51]
## Config

```js
new FileManagerPlugin({
	onEnd: {
		archive: [
			{
				source: './',
				destination: './theme-sniffer.zip',
				options: {
					gzip: true,
					gzipOptions: { level: 1 },
					globOptions: { nomount: true }
				}
			}
		]
	}
})
```

## Issue

Not a bug per se but I'm not sure how to exclude certain folders when archiving.

I'm trying to generate a zip file (and I successfully did) that will have only certain files in it, as for the production purposes they are not needed. In my case I'd like to bundle certain files in a zip file when working on a WordPress plugin.

The snippet above created a zip file with all the files (excluding all the hidden files which is actually a good thing in my case) but it included `node_modules` for instance. And I'd like to avoid that.

Is there an option in the `archive` part of the plugin, or would I need to manually copy needed files `onStart`, then create a zip file from it, and then delete it `onEnd`?

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |    2.0.5     |
| node        |     11.10.0    |
| OS      |     macOS Mojave v10.14.3    |

**Comment by dingo-d** [comment]
Ok so this seems to be working:

```js
new FileManagerPlugin({
  onEnd: [
    {
      copy: [
        {
          source: './',
          destination: './theme-sniffer'
        }
      ]
    },
    {
      delete: [
        './theme-sniffer/assets/dev',
        './theme-sniffer/node_modules',
        './theme-sniffer/composer.json',
        './theme-sniffer/composer.lock',
        './theme-sniffer/package.json',
        './theme-sniffer/package-lock.json',
        './theme-sniffer/phpcs.xml.dist',
        './theme-sniffer/webpack.config.js'
      ]
    },
    {
      archive: [
        {
          source: './theme-sniffer',
          destination: './theme-sniffer.zip',
          options: {
            gzip: true,
            gzipOptions: { level: 1 },
            globOptions: { nomount: true }
          }
        }
      ]
    },
    {
      delete: [
        './theme-sniffer'
      ]
    }

  ]
})
```

If there's a better way I'd be interested in it. If not, feel free to close the issue 🙂

**Comment by sibiraj-s** [comment]
Try. v3. I the ignore option should be working now.

You can do this

```js
[
  {
    source: '/path/',
    destination: '/path/to.tar.gz',
    format: 'tar', // optional
    options: {
      globOptions: {
        ignore: ['theme-sniffer/*'],
      },
    },
  },
];
```
See here for details https://www.archiverjs.com/archiver#glob.

Reopen if it doesn't work.
