### ISSUE TITLE
Archive action terminate too soon

### ISSUE THREAD

**Issue by DavidHenri008** [gregnb/filemanager-webpack-plugin#52]
## Issue
The archive action terminates (call the promise resolve()) when the archiver finalize but this is not really the end of the process since the stream has not been flushed yet. According to the [archiver documentation](https://github.com/archiverjs/node-archiver), the onClose event should be the real end.

I suggest to replace the archive action code:
```
archive.finalize().then(() => resolve());
```
by
```
archive.on('close', () => resolve());
```
Thanks.
## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |   2.0.5    |
| node        |   10.15.3      |
| OS      |    Windows 10    |

**Comment by sibiraj-s** [comment]
Can you try v3. It should be fixed. Reopen the issue if it still exist.
