### ISSUE TITLE
Multiple destinations

### ISSUE THREAD

**Issue by peterchavasse** [gregnb/filemanager-webpack-plugin#55]
Would it be possible to have an array of destinations?

I can of course set up multiple entries in the copy array (which is how I am using the plugin), but would be nicer to have a single entry (as the source files are always the same) which copies the source files to each destination in the new destination array.

Just a thought :)

**Comment by sibiraj-s** [comment]
Yeah, It is a nice to have option. but this would increase the maintenance burden. For now, you can set multiple tasks using existing setup.

Closing this issue for now. If there are multiple requests on this issue. this option can be considered. 

Thanks.
