### ISSUE TITLE
onEnd doesn't work

### ISSUE THREAD

**Issue by GDreyV** [gregnb/filemanager-webpack-plugin#59]
in onEnd handler cb() function is called before operations are finished. It was fixed in following pull request
https://github.com/gregnb/filemanager-webpack-plugin/pull/53 but it's still not applied.

**Comment by sibiraj-s** [comment]
can you check with v3(alpha) and reopen if the problem still persist.

**Comment by EskelCz** [comment]
I'm seeing the same thing with 3.1.0, the onEnd is triggered before the build even starts
