### ISSUE TITLE
Only copy if changed?

### ISSUE THREAD

**Issue by MyNameReallySux** [gregnb/filemanager-webpack-plugin#6]
Hi,

It was using this and noticed there is no option to only copy if changed? Is there a feature like this planned?

It seems not to horrible to implement based on [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin/blob/1ceee6cd3c42f945ad59bd95a193b623ebf48920/src/writeFile.js#L69). I haven't looked at it 100% but essentially it is saving an array of content hashes and comparing them to decide when to copy.

I may attempt this if it is not something you would want to implement, but I don't have time at the moment.

**Comment by gregnb** [comment]
I am using https://github.com/davglass/cpr for copy the utility. It works rather well and at the moment it seems they are not interested supporting that: https://github.com/davglass/cpr/issues/22

**Comment by dtaipov** [comment]
@gregnb You've switched from cpr to cpx and cpx has `--no-initial` flag, which seems like aimed for copying only changed files.
https://github.com/mysticatea/cpx/issues/22#issuecomment-262424231

**Comment by sibiraj-s** [comment]
The tasks runs before and after compilation. I am not sure supporting that would be easier even though the library supports that. 

This issue is quite old, closing this issue for now. This feature can be considered on further requests.
