### ISSUE TITLE
Bug: Move JavaScript / CSS with Sourcemaps

### ISSUE THREAD

**Issue by matthew-kerle** [gregnb/filemanager-webpack-plugin#60]
If you use a setup like:
```js
            onEnd: {
                move: [
                    {
                        source: resolve.public('*.js'),
                        destination: resolve.public('assets/js'),
                    },
                    {
                        source: resolve.public('*.css'),
                        destination: resolve.public('assets/css'),
                    },
                ],
            },
```
And the JS / CSS files have sourcemaps, it will fail to copy because the "file is a directory". What I found worked, was copying the files, and *then* deleting the originals.

**Comment by xianweics** [comment]
You can try to use https://www.npmjs.com/package/filemanager-plugin. Hopefully it fixes your bug.

**Comment by xianweics** [comment]
> If you use a setup like:
> 
> ```js
>             onEnd: {
>                 move: [
>                     {
>                         source: resolve.public('*.js'),
>                         destination: resolve.public('assets/js'),
>                     },
>                     {
>                         source: resolve.public('*.css'),
>                         destination: resolve.public('assets/css'),
>                     },
>                 ],
>             },
> ```
> 
> And the JS / CSS files have sourcemaps, it will fail to copy because the "file is a directory". What I found worked, was copying the files, and _then_ deleting the originals.

You can try to use https://www.npmjs.com/package/filemanager-plugin. Hopefully it fixes your bug.

**Comment by sibiraj-sr** [comment]
Try v3. It is alpha right now. Reopen if the issue still exist.

**Comment by sibiraj-s** [comment]
Try v3. It is in alpha right now. Reopen if the issue still exist.
