### ISSUE TITLE
Supress Move Warnings

### ISSUE THREAD

**Issue by JAW-Dev** [gregnb/filemanager-webpack-plugin#62]
## Config

`N/A`

## Issue

I was wondering if there could be an option to suppress the warning message when move cannot find a file. I have a particular environment where I need to move the CSS/JS files into sub directories. It's fine on a production build or when I start watch, but anytime there are no changes to a file during the watch process and Webpack doesn't build a new file I'm getting the warning in the console. 

I know that the intent, but I know the files aren't there and the warning is unnecessary.

Maybe add a `silent` option to suppress the warnings from printing?

I'd be happy to do a PR for this.

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |  v1.0.26  |
| node        | 10.16.0 |
| OS      | macOS Mojave |

**Comment by sibiraj-s** [comment]
Closing the issue, since this is too old. Try the latest version, there are lot of things changed.
