### ISSUE TITLE
Cannot read property 'isFile' of undefined

### ISSUE THREAD

**Issue by CrazyProgrammer12138** [gregnb/filemanager-webpack-plugin#63]
## Issue
This error occurs when the filemanager-webpack-plugin is installed after the vue is initialized and configured to run

Cannot read property 'isFile' of undefined

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |         |
| node        |         |
| OS      |         |
![image](https://user-images.githubusercontent.com/29749377/68386112-56ba6600-0196-11ea-8a4b-077fafa7af48.png)

**Comment by CrazyProgrammer12138** [comment]
Cannot read property 'isFile' of undefined

**Comment by danieldaeschle** [comment]
anyone knows how to fix?

**Comment by liuning9** [comment]
> anyone knows how to fix?

emmm.. after configuration, you need to build it once..

**Comment by simplethink** [comment]
configureWebpack: config => {
    if (process.env.NODE_ENV === 'production') {
      return {
        plugins: [
          new FileManagerPlugin({
            onEnd: {}
          })
        ]
      }
    } else {

    }

**Comment by simplethink** [comment]
`configureWebpack: config => {
  if (process.env.NODE_ENV === 'production') {
    return {
      plugins: [
        new FileManagerPlugin({
          onEnd: {}
        })
      ]
    }
  } else {

}`

**Comment by simplethink** [comment]
`configureWebpack: config => {
    if (process.env.NODE_ENV === 'production') {
        return {
            plugins: [
                new FileManagerPlugin({
                    onEnd: {}
                })
            ]
        }
    } else {
    }
}`

**Comment by CrazyProgrammer12138** [comment]
是给我的解决办法嘛？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "阿秋"<notifications@github.com&gt;; 
发送时间: 2020年4月15日(星期三) 下午3:32
收件人: "gregnb/filemanager-webpack-plugin"<filemanager-webpack-plugin@noreply.github.com&gt;; 
抄送: "爱@果者。"<1525809031@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gregnb/filemanager-webpack-plugin] Cannot read property &#39;isFile&#39; of undefined (#63)





 
`configureWebpack: config =&gt; {
 if (process.env.NODE_ENV === 'production') {
 return {
 plugins: [
 new FileManagerPlugin({
 onEnd: {}
 })
 ]
 }
 } else {
 
}`

**Comment by cw19931024** [comment]
出现这个问题的根本原因应该是没有做好生产和开发的区分。
导致启动本地项目的时候报错(盲猜应该是没找到生产的文件)
在配置里加个这段代码
`process.env.REACT_APP_COLYST_ENV == 'production'`用来区分生产和开发
在此提供一下config-overrides的配置
![image](https://user-images.githubusercontent.com/15888370/81662936-da6c4c80-9470-11ea-9ea4-a4e0b2431fdb.png)

以下为机翻(The following is machine translation)
The root cause of this problem should be the failure to distinguish between production and development.
Caused an error when starting a local project (the blind guess should be that the production file was not found)
Add this code to the configuration
`process.env.REACT_APP_COLYST_ENV == 'production'` is used to distinguish production and development
Provide the configuration of config-overrides here

**Comment by dsjtlmy** [comment]
我也遇到同样的问题。
最奇葩的是，同一台电脑，第一次检出，run dev 没问题。
但是换一个目录，npm run dev 就报此错误。
真的很迷茫

**Comment by lengziyu** [comment]
## `onEnd.archive`缺少里面设置的`source`参数的文件

比如我的设置是：
```
	new FileManagerPlugin({
		onEnd: {
			delete: [
				'./cai-admin-'+ process.env.VUE_APP_URL +'.zip',
			],
			archive: [
				{source: './dist', destination: './cai-admin-'+process.env.VUE_APP_URL+'.zip'},
			]
                 }
	}) 
```
我把项目根目录的`dist`删除之后，运行`npm run serve`就会报`TypeError: Cannot read property 'isFile' of undefined`

## 解决方法
先`npm run build`出一个`dist`目录，再`npm run serve`就可以了。

**Comment by sibiraj-s** [comment]
I know there is a huge delay in response, recently I was added as collaborator for this lib. I did a rewrite of this plugin and published as v3(alpha). Can you try that. Reopen if the issue still persist.

Thanks.
