### ISSUE TITLE
Copy command now working after webpack build

### ISSUE THREAD

**Issue by taiwoobe** [gregnb/filemanager-webpack-plugin#66]
I have tried running the copy and delete command but when I run my yarn build, it builds my app but the copy path tells me no such path exists. If I run the yarn build again, it now sees to file and copies to the desired destination. 

How can this be fixed without having to run yarn build twice?

**Comment by xianweics** [comment]
> I have tried running the copy and delete command but when I run my yarn build, it builds my app but the copy path tells me no such path exists. If I run the yarn build again, it now sees to file and copies to the desired destination.
> 
> How can this be fixed without having to run yarn build twice?

You can try to use https://www.npmjs.com/package/filemanager-plugin. Hopefully it fixes your bug.

**Comment by wangcherry** [comment]
> I have tried running the copy and delete command but when I run my yarn build, it builds my app but the copy path tells me no such path exists. If I run the yarn build again, it now sees to file and copies to the desired destination.
> 
> How can this be fixed without having to run yarn build twice?

Did you solve it？

**Comment by sibiraj-s** [comment]
@wangcherry can you try v3. It is now in alpha.
