### ISSUE TITLE
Glob expression fatal error

### ISSUE THREAD

**Issue by protyposis** [gregnb/filemanager-webpack-plugin#8]
```js
new FileManagerPlugin({
  onEnd: {
    copy: [
      {source: '/some/path/somefile*', destination: '/some/other/path'},
    ],
  },
});
```

With the above configuration, I get a `Fatal error: Cannot read property 'isFile' of undefined` which happens because `fs.lstat` fails [here](https://github.com/gregnb/filemanager-webpack-plugin/blob/79009c8daa8b9c4ff46b12f6f67a2d33acf16668/src/index.js#L96) when it can't find the path, which it can't since it's a Glob expression. Happens on Windows 10 / Node 6.9.1.

As I temporary workaround, replacing `if (stats.isFile()) {` with `if (!err && stats.isFile()) {` does the trick.

Btw, thanks for writing this plugin, I came here because I've been searching for an alternative to the [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin) that can copy assets after they've been emitted.

**Comment by gregnb** [comment]
Thanks for the feedback. Appreciate it. I just published a new version let me know if this issue is resolved for you

**Comment by protyposis** [comment]
Works great, big thanks for the extremely fast fix & release!

It also made issues #10 and #11 irrelevant for me, very nice :)

**Comment by gregnb** [comment]
Haha no problem. Thanks for the free QA :) I'm going to look over everything once more and push another update later today with fs-extra support
