### ISSUE TITLE
Archive after copy does not work

### ISSUE THREAD

**Issue by ronaldof1s1** [gregnb/filemanager-webpack-plugin#84]
## Config
![image](https://user-images.githubusercontent.com/11231193/98112588-37c1e300-1e81-11eb-888b-3e2acbdd9d1b.png)

## Issue

It does not archive files copied, only the ones pre-existent in the folder. I'm guessing it doesn't finish copying files before it starts zipping them. 

## Your Environment

| Tech                       | Version |
| -------------------------- | ------- |
| filemanager-plugin-webpack |  3.0.0-alpha4       |
| node                       |     11.15    |
| OS                         |     windows 10    |

**Comment by sibiraj-s** [comment]
> I'm guessing it doesn't finish copying files before it starts zipping them.

The copy action is not awaited, hence the issue.

Try aplha.5. Reopen if the issue still exist.
