### ISSUE TITLE
Allow deleting files outside of project directory

### ISSUE THREAD

**Issue by matthiasrohmer** [gregnb/filemanager-webpack-plugin#89]
Deleting paths outside of the CWD is currently not supported. This is caused by `del` which only allows to do so if `force` is passed as an option.

It would be nice if passing this option to the `delete` would be supported.

**Comment by sibiraj-s** [comment]
Try v3.1.0. You can do this.

```js
[
  {
    source: '/path/to/file.txt',
    options: {
      force: true,
    },
  },
];
```

**Comment by matthiasrohmer** [comment]
Nice! Thanks a lot for the quick turn-around 🙂
