### ISSUE TITLE
Support Node v6

### ISSUE THREAD

**Issue by protyposis** [gregnb/filemanager-webpack-plugin#9]
`fs.copyFile` has only been added in Node 8.5 and fails in older versions. Would be helpful to use a 3rd party file copy library for backwards compatibility (e.g. [fs-extra](https://www.npmjs.com/package/fs-extra)) or at least add a helpful error message.

**Comment by gregnb** [comment]
Sounds reasonable to me. I'll look into this today

**Comment by gregnb** [comment]
Swapped in fs-extra and a fix for #11 as well. Version 1.0.16 just published

**Comment by protyposis** [comment]
Very nice, thanks! I already updated to Node v8 so cannot give feedback on that but what I can say is that it still works as expected :)
