### ISSUE TITLE
Can't copy absolute source file if contains glob pattern

### ISSUE THREAD

**Issue by RomanYegay** [gregnb/filemanager-webpack-plugin#93]
## Config

        new FileManagerPlugin({
            events: {
                onEnd: {
                    copy: [
                        {
                            source: 'C:\\temp\\project\\dist\\bundle.{js,css}',
                            destination: ' some destination ',
                        },
                    ],
                },
            },

## Issue

Plugin can't copy absolute file names with glob pattern, i.e.
source: '.\\dist\\bundle.{js,css}' will copy file, but
source: 'C:\\temp\\project\\dist\\bundle.{js,css}' will not

## Your Environment

| Tech                       | Version |
| -------------------------- | ------- |
| filemanager-plugin-webpack | 3.1.0        |
| node                       |  12.2.0       |
| OS                         | Windows10        |

**Comment by sibiraj-s** [comment]
Fixed in v3.1.1
