### ISSUE TITLE
Plugin does not preserve folder structure source vs destination when using the copy event

### ISSUE THREAD

**Issue by yorkish** [gregnb/filemanager-webpack-plugin#94]
## Config

```js
new FileManagerPlugin({
  events: {
    onStart: {
      delete: ["dest/**", "webresources/**"],
    },
    onEnd: {
      copy: [
        {
          source: "sources/images/**/*.{png,gif,jpg,jpeg,ico,svg}",
          destination: "webresources/images",
        },
        {
          source: "dest/fonts",
          destination: "webresources/fonts",
        },
        {
          source: "dest/{main,runtime~main,vendors}.bundle.{js,js.map}",
          destination: "webresources/js",
        },
        {
          source: "dest/*.{css,css.map}",
          destination: "webresources/css",
        },
        {
          source: "dest/webresources/images/**/*.{png,gif,jpg,jpeg,ico,svg}",
          destination: "webresources/images",
        },
      ],
    },
  },
});
```

## Issue

backtracked the issue to v3.0.0-alpha.0 on commit [Replace cpx, remove fs-extra, update ava](https://github.com/gregnb/filemanager-webpack-plugin/pull/82)

basically under 'sources/images' I have additional folders named svg and favicon.

v3.0.0+ using cpy doesn't create those subfolders in the destination folder anymore as cpx did. everything gets mixed up in the same dest folder 'webresouces/images'

## Your Environment

| Tech                       | Version |
| -------------------------- | ------- |
| filemanager-plugin-webpack | 3.1.0   |
| node                       | 10.15.3 |
| OS                         | linux   |

**Comment by sibiraj-s** [comment]
CPX is replaced with CPY since it is no longer maintained. Unfortunately CPY doesn't allow recursive copy. There is an open PR for that in CPY repo. I am waiting on that.

**Comment by zenonhun** [comment]
Any update or workaround for this? CPY doesn't seems to fix this issue anytime soon.

**Comment by sibiraj-s** [comment]
I am afraid we may need to wait on it. I am open to suggestions, let me know if you find anything.

**Comment by adolt** [comment]
Any progress?

**Comment by enkelmedia** [comment]
This one is really limiting, is there any plans to address it?

**Comment by sibiraj-s** [comment]
@enkelmedia the PR to support this feature is done. https://github.com/sindresorhus/cpy/pull/77. It is in review, hoping it would be merged soon. I will release a patch as soon as it is merged.

**Comment by daniel-brenot** [comment]
Bumping because this just ended up causing a delay where i work

**Comment by sibiraj-s** [comment]
Since PR is now merged, I can try making an alpha release pointing to the `cpy's master branch`  .

**Comment by hummal** [comment]
Is anything happening here? Or should we move away from filemanager plugin

**Comment by sibiraj-s** [comment]
Tired of waiting on cpy, and next version is ESM only. hence the package is removed and implemented natively. Try v7 alpha. It by default copies everything recursively, flat option is yet to be implemented.
