### ISSUE TITLE
Unable to move or copy file. No such file exists

### ISSUE THREAD

**Issue by mad-gav** [gregnb/filemanager-webpack-plugin#96]
## Config

    new FileManagerPlugin({
      events: {
        onEnd: {
          move: [
            { source: '/dist/screen.css', destination: '/dist/styles/screen.css' },
          ],
        },
      },
    }),

## Issue

get an error
```
FileManagerPlugin] unable to move /dist/screen.css, Error: ENOENT: no such file or directory, stat '/dist/screen.css'
```
screen.css gets put into the root of /dist in the webpack build
![image](https://user-images.githubusercontent.com/60468535/112615313-3dad6600-8e1a-11eb-889c-1a4cca4e369d.png)

## Your Environment

| Tech                       | Version |
| -------------------------- | ------- |
| filemanager-plugin-webpack | 4.0.0   |
| node                       |    12.16.3     |   |
| OS                         |  OS X catalina        |  |

have tried

/dist
./dist

**Comment by sibiraj-s** [comment]
Hey @mad-gav. I totally missed this one. I hope the issue is resolved.

Reopen if the issue still persists.

**Comment by willdkp** [comment]
@mad-gav did you find a solution to this? I am facing similar problem.
